debug: true
safe: false
markdown: rdiscount

rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants


assets:
  js_compressor:  uglifier
  css_compressor: sass
  dirname: assets
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images

gems:
  - bootstrap-sass
  - rdiscount
  - jekyll
  - jekyll-assets
  - bootstrap-sass
  - compass-rails

cachebust: hard
cache: false

gzip: [ text/css, application/javascript ]

timezone: Europe/Berlin
future: true

exclude:
  - CNAME
  - LICENSE
  - README.md
