safe: true
markdown: kramdown

rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants

assets:
  cache: false
  cachebust: hard
  css_compressor: sass
  debug: true
  dirname: assets
  gzip: [ text/css, application/javascript ]
  js_compressor:  uglifier
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images

gems:
  - bootstrap-sass
  - jekyll
  - jekyll-assets

timezone: Europe/Berlin
future: true

exclude:
  - CNAME
  - LICENSE
  - README.md
