site_name: Developing UXD
description: Learn basic frontend coding skills in no time and improve your work as a User Experience Designer
keywords: "frontend, coding, user experience designer, learn, developing, html, html5, css"
full_url: http://www.developinguxd.com
og_image: "assets/images/open_graph.jpg"
type: website

safe: true
lsi: false
pygments: true
markdown: kramdown

permalink: none

exclude:
  - CNAME
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
  - uninstall_gems.sh
  - config.codekit
